---
abstract: 'Writing PSGI Middleware using simple hooks'
author:
  - 'Peter Makholm <peter@makholm.net>'
  - 'Peter Makholm <peter@makholm.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-EasyHooks
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  homepage: https://github.com/One-com/plack-middleware-easyhooks/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/One-com/plack-middleware-easyhooks.git
    web: https://github.com/One-com/plack-middleware-easyhooks/tree
version: 0.01
